In [3]:
arr1 = np.arange(1, 11)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
arr2 = np.random.randint(1, 10, size=(3, 3))
print(arr2)

[[8 2 9]
 [9 4 2]
 [5 1 9]]


In [5]:
print("Sum:", np.sum(arr1))
print("Mean:", np.mean(arr1))
print("Max:", np.max(arr1))

Sum: 55
Mean: 5.5
Max: 10


In [6]:
arr1_times_2 = arr1 * 2
print(arr1_times_2)

[ 2  4  6  8 10 12 14 16 18 20]


In [7]:
arr1_modified = arr1.copy()
arr1_modified[arr1_modified > 5] = 0
print(arr1_modified)

[1 2 3 4 5 0 0 0 0 0]
